### PR TITLE
docs and NEWS updates

### PR DESCRIPTION
**Pull request by balejk**
- **docs: remove permission-granting specification from the protocol doc**
- **NEWS: add a missing changelog entry for permissions**

### CODE REVIEW

**Comment by meejah** [comment]
Ah, I see that should have gone in the `frontend-protocol.rst` instead

**Comment by balejk** [comment]
I originally thought that more or less the same information is already
present there but that's not actually fully correct so a move rather
than deletion would indeed probably be better.

I can try to mix it into the "kind": "grant-permission" section of the
other document if you agree or I can just let you edit it to your liking
:-) Please let me know what you prefer.

**Comment by meejah** [comment]
If you're happy to do it, that would be great!

Please also make any other edits / simplifications / clarifications you think are good. I cannot look with "fresh" eyes anymore, and can always do other editing later

thanks!

**Comment by meejah** [comment]
Great, thanks. Above change looks good too.

I think the only thing potentially missing in mention of `"kind": "danger-disable-permission-check"`

:tada:

**Comment by balejk** [comment]
I have added the removal.

> I think the only thing potentially missing in mention of `"kind": "danger-disable-permission-check"`

Well there is a whole section about that right under the "kind:
grant-permission" one :-) Or do you mean something else?

**Comment by meejah** [comment]
Yeah, I mean it needs another title for `"kind": "danger-disable-permission-check"` (that's two different messages, on called `"grant-permission"` and one called `"danger-disable-permission-check"` that turns off all permission checking).

Thanks!

**Comment by balejk** [comment]
Sorry, I still don't follow. Where would you like me to add this
title/section? As I said, it is already in frontend-protocol.rst just
below the grant-permission section.

**Comment by meejah** [comment]
Ah, sorry my bad I was just looking at the diff not the rendered docs.

Thanks again!

**Pull request merged**
