### PR TITLE
More refactor

### PR DESCRIPTION
**Pull request by meejah**
Further to comments at the bottom of #14

### CODE REVIEW

**Comment by meejah** [comment]
Pro: way simpler.

Con: there's no way to have "also some subcommands" (so `readme` and `tui` have to go somewhere ... else?)

**Comment by meejah** [comment]
Hmm, I can't "request review" from @balejk for some reason, but would appreciate any thoughts!

**Comment by balejk** [comment]
Yes, this is what I meant.

I tried out the TUI and since it's not exactly a full blown TUI but
rather a kind of REPL, how about making it `fowl -i/--interactive`
rather than an additional entry point?

**Comment by meejah** [comment]
yeah that makes sense (and I _have_ thought of making "a real TUI" but that might actually live better as a separate project since it'll probably have way more dependencies :grimacing: )

**Comment by balejk** [comment]
> (and I _have_ thought of making "a real TUI" but that might actually live better as a separate project since it'll probably have way more dependencies :grimacing: )

I completely agree!

I like this as it is with your latest commit :-)

**Pull request merged**
